In [1]:
import pandas as pd 
import numpy as np

In [2]:
ds=pd.read_csv(r"C:\Users\Harsha reddy\Downloads\bank.csv")

In [3]:
ds.head(10)

age         job   marital  education default  balance housing loan  \
0   59      admin.   married  secondary      no     2343     yes   no   
1   56      admin.   married  secondary      no       45      no   no   
2   41  technician   married  secondary      no     1270     yes   no   
3   55    services   married  secondary      no     2476     yes   no   
4   54      admin.   married   tertiary      no      184      no   no   
5   42  management    single   tertiary      no        0     yes  yes   
6   56  management   married   tertiary      no      830     yes  yes   
7   60     retired  divorced  secondary      no      545     yes   no   
8   37  technician   married  secondary      no        1     yes   no   
9   28    services    single  secondary      no     5090     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may      1042         1     -1         0  unknown     yes  
1  unknown    5   may      1467         1     -1         0  unknown     yes  
2  unknown    5   may      1389         1     -1         0  unknown     yes  
3  unknown    5   may       579         1     -1         0  unknown     yes  
4  unknown    5   may       673         2     -1         0  unknown     yes  
5  unknown    5   may       562         2     -1         0  unknown     yes  
6  unknown    6   may      1201         1     -1         0  unknown     yes  
7  unknown    6   may      1030         1     -1         0  unknown     yes  
8  unknown    6   may       608         1     -1         0  unknown     yes  
9  unknown    6   may      1297         3     -1         0  unknown     yes

In [4]:
ds.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [5]:
ds.head(3)

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes

In [6]:
ds.drop(['job'],axis=1,inplace=True)
ds.drop(['default'],axis=1,inplace=True)
ds.drop(['month'],axis=1,inplace=True)
ds.drop(['poutcome'],axis=1,inplace=True)
ds.drop(['marital'],axis=1,inplace=True)

In [7]:
ds.head(5)

age  education  balance housing loan  contact  day  duration  campaign  \
0   59  secondary     2343     yes   no  unknown    5      1042         1   
1   56  secondary       45      no   no  unknown    5      1467         1   
2   41  secondary     1270     yes   no  unknown    5      1389         1   
3   55  secondary     2476     yes   no  unknown    5       579         1   
4   54   tertiary      184      no   no  unknown    5       673         2   

   pdays  previous deposit  
0     -1         0     yes  
1     -1         0     yes  
2     -1         0     yes  
3     -1         0     yes  
4     -1         0     yes

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds['education']=le.fit_transform(ds['education'])
ds['housing']=le.fit_transform(ds['housing'])
ds['loan']=le.fit_transform(ds['loan'])
ds['contact']=le.fit_transform(ds['contact'])
ds['deposit']=le.fit_transform(ds['deposit'])

In [9]:
ds.head(5)

age  education  balance  housing  loan  contact  day  duration  campaign  \
0   59          1     2343        1     0        2    5      1042         1   
1   56          1       45        0     0        2    5      1467         1   
2   41          1     1270        1     0        2    5      1389         1   
3   55          1     2476        1     0        2    5       579         1   
4   54          2      184        0     0        2    5       673         2   

   pdays  previous  deposit  
0     -1         0        1  
1     -1         0        1  
2     -1         0        1  
3     -1         0        1  
4     -1         0        1

In [11]:
ds.shape

(11162, 12)

In [14]:
x=ds.iloc[:,0:11].values
y=ds.iloc[:,11].values

In [15]:
x

array([[  59,    1, 2343, ...,    1,   -1,    0],
       [  56,    1,   45, ...,    1,   -1,    0],
       [  41,    1, 1270, ...,    1,   -1,    0],
       ...,
       [  32,    1,   29, ...,    2,   -1,    0],
       [  43,    1,    0, ...,    2,  172,    5],
       [  34,    1,    0, ...,    1,   -1,    0]], dtype=int64)

In [16]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100000)

In [28]:
x_train

array([[  37,    0,  461, ...,    2,   -1,    0],
       [  37,    1,  565, ...,    1,   93,    3],
       [  43,    2, 1059, ...,    2,   -1,    0],
       ...,
       [  37,    2, 2987, ...,    1,   87,   10],
       [  31,    1,  216, ...,    1,   -1,    0],
       [  30,    1,  192, ...,    1,   -1,    0]], dtype=int64)

In [29]:
y_train

array([0, 1, 1, ..., 1, 0, 0])

In [30]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

C:\Users\Harsha reddy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
ypred=logreg.predict(x_test)

In [32]:
ypred

array([0, 1, 1, ..., 0, 0, 1])

In [33]:
y_test

array([0, 1, 1, ..., 1, 0, 1])

In [34]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ypred,y_test)

In [35]:
accuracy

0.8029556650246306

In [36]:
ds.head(1)

age  education  balance  housing  loan  contact  day  duration  campaign  \
0   59          1     2343        1     0        2    5      1042         1   

   pdays  previous  deposit  
0     -1         0        1

In [41]:
logreg.predict([[20,2,134,0,1,0,4,1000,0,2,1]])

array([1])